@apiUrl = http://localhost:3000/api/autores
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzM2MWMxZDg1NGRjOGQ1N2E0NmFjMTIiLCJub21lIjoiRWR1YXJkbyBCb25hbWlnbyBCaWFuY2hldHRpIiwiaWF0IjoxNjY0NDk2MzYyLCJleHAiOjE2NjQ0OTk5NjJ9.PcOOt7GnfGpkwspc8cccGINQf30frk0xzzmtdUmOIuA

# Listar autores
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo autor
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Fulano", 
 "dataNascimento": "04/09/2001"
}
###

# Alterar autor
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "631143dedadef46c7db2a34f",
 "nome": "Fulano Editado", 
 "dataNascimento": "04/09/2001"
}

###
# Excluir um autor
DELETE {{apiUrl}}/63114d6755c23104eed04967
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id do autor
GET {{apiUrl}}/631143dedadef46c7db2a34f
Content-Type: application/json
x-auth-token: {{authToken}}

###
# Obter autores filtrando
GET {{apiUrl}}/filtro/Editad
Content-Type: application/json
x-auth-token: {{authToken}}
###