@apiUrl = http://localhost:3000/api/midiasusuarios
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzM2MWMxZDg1NGRjOGQ1N2E0NmFjMTIiLCJub21lIjoiRWR1YXJkbyBCb25hbWlnbyBCaWFuY2hldHRpIiwiaWF0IjoxNjY4NTQzNzcwLCJleHAiOjE2Njg1NDczNzB9.O27LH6I8xbwDbFkrPsAmu-fnftzSH9ivyFPxohhMIDA

# Listar midias de usuários
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novas midias de usuários
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "status": "Em Andamento", 
 "nota": 9.8, 
 "midia": "6373d17b7a1389a91881b531",
 "usuario": "63361c1d854dc8d57a46ac12"
}
###

# Alterar midias de usuários
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "6373d3c443d8b708e89b43e1",
 "status": "Em Andamento Editado", 
 "nota": 9.9, 
 "midia": "6373d17b7a1389a91881b531",
 "usuario": "63361c1d854dc8d57a46ac12"
}

###
# Excluir midias de usuários
DELETE {{apiUrl}}/6373d36343d8b708e89b43c9
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de midias de usuários
GET {{apiUrl}}/6373d3c443d8b708e89b43e1
Content-Type: application/json
x-auth-token: {{authToken}}

###
# Obter midias de usuários filtrando
GET {{apiUrl}}/filtro/Editad
Content-Type: application/json
x-auth-token: {{authToken}}
###

###
# Favoritar midias de usuários
GET {{apiUrl}}/favoritar/6373d6e543d8b708e89b442f
Content-Type: application/json
x-auth-token: {{authToken}}
###

###
# Listar favoritos do usuário
GET {{apiUrl}}/listfavoritos/63361c1d854dc8d57a46ac12
Content-Type: application/json
x-auth-token: {{authToken}}
###

###
# Nota média de uma mídia
GET {{apiUrl}}/notamedia/6377eba67e849f60af6ad6c7
Content-Type: application/json
x-auth-token: {{authToken}}
###