@apiUrl = http://localhost:3000/api/produtosusuarios
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzM2MWMxZDg1NGRjOGQ1N2E0NmFjMTIiLCJub21lIjoiRWR1YXJkbyBCb25hbWlnbyBCaWFuY2hldHRpIiwiaWF0IjoxNjY1OTcwMDgzLCJleHAiOjE2NjU5NzM2ODN9.SzPwXqPnu1kF5W9MiNu3JdncvfU-nZ3hPw1Z_jsJxqc

# Listar produtos de usuários
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo produtos de usuários
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "status": "Em Andamento", 
 "nota": 9.8, 
 "produto": "6311518d2e904763195fedc3",
 "usuario": "63081231de51fac3d19860c7"
}
###

# Alterar produtos de usuários
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "631155047dc28eb285d86489",
 "status": "Em Andamento Editado", 
 "nota": 9.9, 
 "produto": "6311518d2e904763195fedc3",
 "usuario": "63081231de51fac3d19860c7"
}

###
# Excluir produtos de usuários
DELETE {{apiUrl}}/631155047dc28eb285d86489
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de produtos de usuários
GET {{apiUrl}}/631155047dc28eb285d86489
Content-Type: application/json
x-auth-token: {{authToken}}

###
# Obter produtos de usuários filtrando
GET {{apiUrl}}/filtro/Editad
Content-Type: application/json
x-auth-token: {{authToken}}
###