@apiUrl = http://localhost:3000/api/usuarios
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzM2MWMxZDg1NGRjOGQ1N2E0NmFjMTIiLCJub21lIjoiRWR1YXJkbyBCb25hbWlnbyBCaWFuY2hldHRpIiwiaWF0IjoxNjY4ODA2MjE1LCJleHAiOjE2Njg4MDk4MTV9.5VeOSnxP8Z_7QjeFPINJ6ExYdM0b0_AXIgAp91KuRtw

# Listar usuários
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo usuário
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Eduardo Bonamigo Bianchetti", 
 "email": "185961@upf.br",
 "senha": "123",
 "dataNascimento": "04/09/2001"
}
###

# Alterar usuário
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "631a7f04b2cad62388da5e6e",
 "nome": "Eduardo Bonamigo Bianchetti", 
 "email": "185961@upf.br",
 "senha": "123",
 "dataNascimento": "04/09/2001"
}

###
# Excluir um usuário
DELETE {{apiUrl}}/6377faf04cd45e00ad1bdef0
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id do usuário
GET {{apiUrl}}/63080d1bb0b2d0e988a0bae4
Content-Type: application/json
x-auth-token: {{authToken}}

###
# Obter usuários filtrando
GET {{apiUrl}}/filtro/185961
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Autenticação de usuário
POST http://localhost:3000/api/login
Content-Type: application/json

{
 "email": "admin@admin",
 "senha": "123"
}
###

# Autenticação de usuário ADMIN
POST http://localhost:3000/api/loginAdmin
Content-Type: application/json

{
 "email": "185961@upf.br",
 "senha": "123"
}
###

# Registrar sem token
POST http://localhost:3000/api/register
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Teste", 
 "email": "teste@upf.br",
 "senha": "123",
 "dataNascimento": "04/09/2001"
}
###