@apiUrl = http://localhost:3000/api/usuarios

# Listar usuários
GET {{apiUrl}}
Content-Type: application/json
###

# Inserir novo usuário
POST {{apiUrl}}
Content-Type: application/json

{
 "nome": "Eduardo Bonamigo Bianchetti", 
 "email": "185961@upf.br",
 "senha": "123",
 "dataNascimento": "04/09/2001"
}
###

# Alterar usuário
PUT {{apiUrl}}
Content-Type: application/json

{
 "_id": "63080c22b0b2d0e988a0bad2",
 "nome": "Eduardo Bonamigo Bianchetti", 
 "email": "185961@upf.br",
 "senha": "12345",
 "dataNascimento": "04/09/2001"
}

###
# Excluir um usuário
DELETE {{apiUrl}}/630811b1ccc973e7cdd890e3
Content-Type: application/json
###

# Obter pelo id do usuário
GET {{apiUrl}}/63080d1bb0b2d0e988a0bae4
Content-Type: application/json

###
# Obter usuários filtrando
GET {{apiUrl}}/filtro/185961
Content-Type: application/json
###

# Autenticação de usuário
POST {{apiUrl}}/login
Content-Type: application/json

{
 "email": "185961@upf.br",
 "senha": "123"
}
###